//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameMove
    {
        public long MoveID { get; set; }
        public long NumberGame { get; set; }
        public long NumberMove { get; set; }
        public string GameMove1 { get; set; }
        public Nullable<System.DateTime> TimeLeft { get; set; }
        public string Comment { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
