//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersOld
    {
        public long PlayerId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Country { get; set; }
        public byte Gender { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public byte RankPlayer { get; set; }
        public short Rating { get; set; }
        public Nullable<int> NumberGames { get; set; }
        public Nullable<int> NumberWins { get; set; }
        public Nullable<int> NumberDraw { get; set; }
        public Nullable<int> NumberDefeat { get; set; }
    }
}
